#!/usr/bin/env python3

import os
import os.path


Import('env')

env.Append(BUILDERS =
	{'CapnP' : Builder(action = 'capnp compile -oc++ $SOURCE',
		suffix='.capnp.c++', src_suffix='.capnp')})

env.CapnP('JsonRpc.capnp')

env.Append(BUILDERS =
	{'CapnPMv' : Builder(action = 'cp $SOURCE $TARGET',
		suffix='.capnp.cpp', src_suffix='.capnp.c++')})

env.CapnPMv('JsonRpc.capnp.c++')

dir_path = Dir('.').abspath
env.protocol_sources = [dir_path + "/JsonRpc.capnp.cpp"]
