#!/usr/bin/env python3

import os
import os.path
import glob


Import('env')

env_util = env.Clone()

dir_path = Dir('.').abspath
env.util_sources = sorted(glob.glob(dir_path + "/*.cpp"))
env.util_header = sorted(glob.glob(dir_path + "/*.h"))

env.util_static_lib = env_util.StaticLibrary('genral-util', env.util_sources )
env.util_shared_lib = env_util.SharedLibrary('genral-util', env.util_sources )
