#!/usr/bin/env python3

Import('env')

env_core = env.Clone()

env.core_sources = [
            'JsonRpcAdapter.cpp','JsonRpcService.cpp','Bouncer.cpp', 
            'JsonRpcCodecHandler.cpp'
        ]

#lib_static = env_util.add_library("genral-util", env.util_sources)
#lib_shared = env_util.add_library("genral-util", env.util_sources,shared=True)

env_core.StaticLibrary('genral-api', env.core_sources )
env_core.SharedLibrary('genral-api', env.core_sources )
