#!/usr/bin/env python3

import os
import os.path


Import('env')

env_core = env.Clone()

dir_path = Dir('.').abspath
env.core_sources = sorted(glob.glob(dir_path + "/" + "*.cpp"))

env.core_sources.append(env.protocol_sources);

env_core.StaticLibrary('genral-api', env.core_sources )
env_core.SharedLibrary('genral-api', env.core_sources )
